<a href="https://colab.research.google.com/github/SirineMaaroufi/Data-Analysis-by-Omar-Souissi/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CHAP 3: Pandas

In [1]:
import pandas as pd

### Series

In [2]:
ser = pd.Series([1,3,5,7,9],name='impaires')

In [3]:
ser

0    1
1    3
2    5
3    7
4    9
Name: impaires, dtype: int64

In [4]:
ser.values

array([1, 3, 5, 7, 9])

In [5]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
ser[2]

5

In [7]:
ser[0:3]

0    1
1    3
2    5
Name: impaires, dtype: int64

In [8]:
ser = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd','e'])

In [9]:
ser

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [10]:
pib_dict={'État-Unis':18624.48,'Japon':4936.21,'Chine':11218.28,'Allemagne':3477.8,'Royaume-Uni':2647.9} 

In [11]:
pib = pd.Series(pib_dict)
pib

État-Unis      18624.48
Japon           4936.21
Chine          11218.28
Allemagne       3477.80
Royaume-Uni     2647.90
dtype: float64

In [12]:
pib['Japon']

4936.21

In [13]:
pib['État-Unis':'Chine']

État-Unis    18624.48
Japon         4936.21
Chine        11218.28
dtype: float64

In [14]:
pib[1:3]

Japon     4936.21
Chine    11218.28
dtype: float64

### Dataframes

In [15]:
pibpop_dict={'État-Unis':57638,'Japon':38972,'Chine':8117,'Allemagne':42232,'Royaume-Uni':40412}
pibpop = pd.Series(pibpop_dict)

In [16]:
pib_pop = pd.DataFrame({'pib/habitant': pibpop, 'pib': pib})
pib_pop

pib/habitant       pib
État-Unis           57638  18624.48
Japon               38972   4936.21
Chine                8117  11218.28
Allemagne           42232   3477.80
Royaume-Uni         40412   2647.90

In [17]:
pib_pop.columns

Index(['pib/habitant', 'pib'], dtype='object')

In [18]:
pib_pop.index

Index(['État-Unis', 'Japon', 'Chine', 'Allemagne', 'Royaume-Uni'], dtype='object')

In [19]:
pib_pop['pib/habitant']

État-Unis      57638
Japon          38972
Chine           8117
Allemagne      42232
Royaume-Uni    40412
Name: pib/habitant, dtype: int64

In [20]:
pd.DataFrame([{'alex': 12, 'ibrahim': 11, 'sara': 15}, {'alex': 14, 'ibrahim': 15}, {'alex': 15, 'sara': 16}],index=['Français', 'Mathématiques', 'Anglais'])

alex  ibrahim  sara
Français         12     11.0  15.0
Mathématiques    14     15.0   NaN
Anglais          15      NaN  16.0

In [22]:
import numpy as np

In [23]:
pd.DataFrame(np.random.rand(2, 2),columns=['e1', 'e2'],index=['a', 'b']) 

e1        e2
a  0.176800  0.008417
b  0.645843  0.403593

In [24]:
ind = pd.Index(['Français', 'Mathématiques', 'Anglais'])

In [25]:
ind[2]

'Anglais'

In [26]:
ind[2::]

Index(['Anglais'], dtype='object')

In [27]:
print(ind.size,"&" ,ind.shape, "&" ,ind.ndim, "&" ,ind.dtype)

3 & (3,) & 1 & object


In [28]:
ind1 = pd.Index(['Français', 'Mathématiques', 'Anglais'])
ind2 = pd.Index(['Français', 'Sciences'])

In [29]:
ind1 & ind2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  """Entry point for launching an IPython kernel.


Index(['Français'], dtype='object')

In [30]:
ind1 | ind2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  """Entry point for launching an IPython kernel.


Index(['Anglais', 'Français', 'Mathématiques', 'Sciences'], dtype='object')

In [31]:
ind1 ^ ind2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  """Entry point for launching an IPython kernel.


Index(['Anglais', 'Mathématiques', 'Sciences'], dtype='object')

### Indexer et Sélectionner des données

In [32]:
ser = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd','e'])

In [33]:
ser

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [34]:
ser['c']

5

In [35]:
'b' in ser

True

In [36]:
ser.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [37]:
list(ser.items())

[('a', 1), ('b', 3), ('c', 5), ('d', 7), ('e', 9)]

In [38]:
ser['e'] = 11
ser

a     1
b     3
c     5
d     7
e    11
dtype: int64

In [39]:
ser[(ser > 1) & (ser < 11)]

b    3
c    5
d    7
dtype: int64

In [40]:
ser[['a', 'e']]

a     1
e    11
dtype: int64

In [41]:
ser = pd.Series(['a', 'b', 'c', 'd','e'], index=[1, 3, 5, 7, 9])

In [42]:
ser[1]

'a'

In [43]:
ser.loc[1]

'a'

In [44]:
ser.iloc[1] # en réalité 'a' se situe à la position 0

'b'

In [45]:
pib = pd.Series({'État-Unis':18624.48,'Japon':4936.21,'Chine':11218.28,'Allemagne':3477.8,'Royaume-Uni':2647.9})
pibpop = pd.Series({'État-Unis':57638,'Japon':38972,'Chine':8117,'Allemagne':42232,'Royaume-Uni':40412})
pib_pop = pd.DataFrame({'pib/habitant': pibpop, 'pib': pib})
pib_pop

pib/habitant       pib
État-Unis           57638  18624.48
Japon               38972   4936.21
Chine                8117  11218.28
Allemagne           42232   3477.80
Royaume-Uni         40412   2647.90

In [46]:
pib_pop['pib']

État-Unis      18624.48
Japon           4936.21
Chine          11218.28
Allemagne       3477.80
Royaume-Uni     2647.90
Name: pib, dtype: float64

In [47]:
pib_pop['population'] = (pib_pop['pib']*100000000) / pib_pop['pib/habitant']

In [48]:
pib_pop

pib/habitant       pib    population
État-Unis           57638  18624.48  3.231285e+07
Japon               38972   4936.21  1.266604e+07
Chine                8117  11218.28  1.382072e+08
Allemagne           42232   3477.80  8.234988e+06
Royaume-Uni         40412   2647.90  6.552262e+06

In [49]:
pib_pop.values

array([[5.76380000e+04, 1.86244800e+04, 3.23128492e+07],
       [3.89720000e+04, 4.93621000e+03, 1.26660423e+07],
       [8.11700000e+03, 1.12182800e+04, 1.38207219e+08],
       [4.22320000e+04, 3.47780000e+03, 8.23498769e+06],
       [4.04120000e+04, 2.64790000e+03, 6.55226170e+06]])

In [50]:
pib_pop.T

État-Unis         Japon         Chine     Allemagne  \
pib/habitant  5.763800e+04  3.897200e+04  8.117000e+03  4.223200e+04   
pib           1.862448e+04  4.936210e+03  1.121828e+04  3.477800e+03   
population    3.231285e+07  1.266604e+07  1.382072e+08  8.234988e+06   

               Royaume-Uni  
pib/habitant  4.041200e+04  
pib           2.647900e+03  
population    6.552262e+06

In [51]:
pib_pop.T.iloc[:2, :3]

État-Unis     Japon     Chine
pib/habitant   57638.00  38972.00   8117.00
pib            18624.48   4936.21  11218.28

In [52]:
pib_pop.T.loc[:'pib/habitant', :'Chine']

État-Unis    Japon   Chine
pib/habitant    57638.0  38972.0  8117.0

In [53]:
pib_pop[pib_pop['population'] > 100000000]

pib/habitant       pib    population
Chine          8117  11218.28  1.382072e+08

### Calcul

In [54]:
import pandas as pd

In [55]:
import numpy as np

In [56]:
r1 = np.arange(0, 18, 2)
r1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [57]:
ser = pd.Series(r1)
ser

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
dtype: int64

In [58]:
df = pd.DataFrame(r1.reshape(3, 3),columns=['A', 'B', 'C'])

In [59]:
df

A   B   C
0   0   2   4
1   6   8  10
2  12  14  16

In [60]:
np.power(ser,2)

0      0
1      4
2     16
3     36
4     64
5    100
6    144
7    196
8    256
dtype: int64

In [61]:
np.add(df,2)

A   B   C
0   2   4   6
1   8  10  12
2  14  16  18

In [62]:
np.sin(df*np.pi)

A             B             C
0  0.000000e+00 -2.449294e-16 -4.898587e-16
1 -7.347881e-16 -9.797174e-16 -1.224647e-15
2 -1.469576e-15 -1.714506e-15 -1.959435e-15

In [63]:
pib = pd.Series({'État-Unis':18624.48,'Chine':11218.28,'Royaume-Uni':2647.9}, name='pib')

In [64]:
pibpop = pd.Series({'État-Unis':57638,'Japon':38972,'Chine':8117,'Allemagne':42232}, name='pib/habitant')

In [65]:
pib*100000000/pibpop

Allemagne               NaN
Chine          1.382072e+08
Japon                   NaN
Royaume-Uni             NaN
État-Unis      3.231285e+07
dtype: float64

In [66]:
r2 = np.arange(0, 20, 2)

In [67]:
df1 = pd.DataFrame(r2.reshape(5, 2),columns=['A','B'])
df1

A   B
0   0   2
1   4   6
2   8  10
3  12  14
4  16  18

In [68]:
df2 = pd.DataFrame(r2.reshape(2, 5),columns=['A','B','C','D','E'])
df2

A   B   C   D   E
0   0   2   4   6   8
1  10  12  14  16  18

In [69]:
df1 + df2

A     B   C   D   E
0   0.0   4.0 NaN NaN NaN
1  14.0  18.0 NaN NaN NaN
2   NaN   NaN NaN NaN NaN
3   NaN   NaN NaN NaN NaN
4   NaN   NaN NaN NaN NaN

In [70]:
df3= df1.add(df2, fill_value=0)
df3

A     B     C     D     E
0   0.0   4.0   4.0   6.0   8.0
1  14.0  18.0  14.0  16.0  18.0
2   8.0  10.0   NaN   NaN   NaN
3  12.0  14.0   NaN   NaN   NaN
4  16.0  18.0   NaN   NaN   NaN

### Manipuler les données manquantes

In [71]:
import pandas as pd
import numpy as np

In [72]:
ar = np.array([0, 1, 2, 3])
ar

array([0, 1, 2, 3])

In [73]:
ar1 = np.array([0, 1, None, 3])
ar1

array([0, 1, None, 3], dtype=object)

In [74]:
ar.mean()

1.5

In [75]:
ar1.mean()

TypeError: ignored

In [76]:
ar2 = np.array([0, 1, np.nan, 3])
ar2

array([ 0.,  1., nan,  3.])

In [77]:
ar2.mean()

nan

In [78]:
np.nanmean(ar2)

1.3333333333333333

In [79]:
ser2 = pd.Series([np.nan, 'Bonjour',2, None])

In [80]:
ser2 + ser2

0               NaN
1    BonjourBonjour
2                 4
3               NaN
dtype: object

In [81]:
ser2.isnull()

0     True
1    False
2    False
3     True
dtype: bool

In [82]:
ser2.notnull()

0    False
1     True
2     True
3    False
dtype: bool

In [83]:
ser2[ser2.notnull()]

1    Bonjour
2          2
dtype: object

In [84]:
ser2.dropna()

1    Bonjour
2          2
dtype: object

In [87]:
ser2.fillna(0)

0          0
1    Bonjour
2          2
3          0
dtype: object

In [88]:
df1=pd.DataFrame([[1, np.nan, 3], [4, 5, 6], [np.nan, 8, 9]])
df1

0    1  2
0  1.0  NaN  3
1  4.0  5.0  6
2  NaN  8.0  9

In [89]:
df1.dropna()

0    1  2
1  4.0  5.0  6

In [90]:
df1.dropna(axis=1)

2
0  3
1  6
2  9

In [91]:
df1.fillna(0)

0    1  2
0  1.0  0.0  3
1  4.0  5.0  6
2  0.0  8.0  9

In [92]:
df1.fillna({0:'Abs',1:99})

0     1  2
0  1.0  99.0  3
1  4.0   5.0  6
2  Abs   8.0  9

### Concaténer différentes sources de données

In [93]:
import pandas as pd
import numpy as np

In [94]:
ar1 = np.arange(2,20,2).reshape(3,3)

In [95]:
ar2 = ar1 + 1

In [96]:
np.concatenate([ar1,ar2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [97]:
np.concatenate([ar1,ar2],axis=1)

array([[ 2,  4,  6,  3,  5,  7],
       [ 8, 10, 12,  9, 11, 13],
       [14, 16, 18, 15, 17, 19]])

In [102]:
ser1 = pd.Series(np.random.rand(3), index=[1,2,3])
ser1

1    0.003187
2    0.848064
3    0.066000
dtype: float64

In [101]:
ser2 = pd.Series(np.random.rand(3), index=[4,5,6])
ser2

4    0.972203
5    0.738100
6    0.671827
dtype: float64

In [103]:
pd.concat([ser1,ser2])

1    0.003187
2    0.848064
3    0.066000
4    0.972203
5    0.738100
6    0.671827
dtype: float64

In [104]:
pd.concat([ser1,ser2],axis=1)

0         1
1  0.003187       NaN
2  0.848064       NaN
3  0.066000       NaN
4       NaN  0.972203
5       NaN  0.738100
6       NaN  0.671827

In [105]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.003187
   2    0.848064
   3    0.066000
2  4    0.972203
   5    0.738100
   6    0.671827
dtype: float64

In [108]:
df1 = pd.DataFrame(ar1, index=[1,2,3],columns=['A','B','C'])
df1

A   B   C
1   2   4   6
2   8  10  12
3  14  16  18

In [109]:
df2 = pd.DataFrame(ar2, index=[4,5,6],columns=['A','B','C'])
df2

A   B   C
4   3   5   7
5   9  11  13
6  15  17  19

In [110]:
pd.concat([df1,df2])

A   B   C
1   2   4   6
2   8  10  12
3  14  16  18
4   3   5   7
5   9  11  13
6  15  17  19

In [112]:
pd.concat([df1,df2], axis=1)

A     B     C     A     B     C
1   2.0   4.0   6.0   NaN   NaN   NaN
2   8.0  10.0  12.0   NaN   NaN   NaN
3  14.0  16.0  18.0   NaN   NaN   NaN
4   NaN   NaN   NaN   3.0   5.0   7.0
5   NaN   NaN   NaN   9.0  11.0  13.0
6   NaN   NaN   NaN  15.0  17.0  19.0

In [116]:
df3 = pd.DataFrame(ar2, index=[2,3,4],columns=['A','B','C'])
df3

A   B   C
2   3   5   7
3   9  11  13
4  15  17  19

In [114]:
pd.concat([df1,df3])

A   B   C
1   2   4   6
2   8  10  12
3  14  16  18
2   3   5   7
3   9  11  13
4  15  17  19

In [117]:
try: pd.concat([df1, df3], verify_integrity=True)
except ValueError as e: print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([2, 3], dtype='int64')


### Fusion

In [118]:
df1 = pd.DataFrame({'Salarié': ['Eric', 'Hapsa', 'Elise', 'Xin'], 'groupe': ['Technicien', 'Ingénieur', 'Ingénieur', 'Technicien']})
df1

Salarié      groupe
0    Eric  Technicien
1   Hapsa   Ingénieur
2   Elise   Ingénieur
3     Xin  Technicien

In [119]:
df2 = pd.DataFrame({'Salarié': ['Hapsa', 'Elise', 'Eric', 'Xin'], 'date_embauche': [2001, 1988, 2012, 2016]})
df2

Salarié  date_embauche
0   Hapsa           2001
1   Elise           1988
2    Eric           2012
3     Xin           2016

In [120]:
df3 = pd.merge(df1, df2)

In [121]:
df3

Salarié      groupe  date_embauche
0    Eric  Technicien           2012
1   Hapsa   Ingénieur           2001
2   Elise   Ingénieur           1988
3     Xin  Technicien           2016

In [122]:
df4 = pd.DataFrame({'groupe': ['Technicien', 'Ingénieur'], 'Superviseur': ['Carlos', 'Amine']})
df4

groupe Superviseur
0  Technicien      Carlos
1   Ingénieur       Amine

In [123]:
print(pd.merge(df3, df4))

  Salarié      groupe  date_embauche Superviseur
0    Eric  Technicien           2012      Carlos
1     Xin  Technicien           2016      Carlos
2   Hapsa   Ingénieur           2001       Amine
3   Elise   Ingénieur           1988       Amine


In [125]:
df5 = pd.DataFrame({'groupe': ['Technicien', 'Technicien', 'Ingénieur', 'Ingénieur', 'Ingénieur'], 'compétences': ['tableurs', 'maintenance', 'codage', 'conduite de changement',
'recherche opérationelle']})
df5

groupe              compétences
0  Technicien                 tableurs
1  Technicien              maintenance
2   Ingénieur                   codage
3   Ingénieur   conduite de changement
4   Ingénieur  recherche opérationelle

In [126]:
print(pd.merge(df3, df5))

  Salarié      groupe  date_embauche              compétences
0    Eric  Technicien           2012                 tableurs
1    Eric  Technicien           2012              maintenance
2     Xin  Technicien           2016                 tableurs
3     Xin  Technicien           2016              maintenance
4   Hapsa   Ingénieur           2001                   codage
5   Hapsa   Ingénieur           2001   conduite de changement
6   Hapsa   Ingénieur           2001  recherche opérationelle
7   Elise   Ingénieur           1988                   codage
8   Elise   Ingénieur           1988   conduite de changement
9   Elise   Ingénieur           1988  recherche opérationelle


In [128]:
df6= pd.DataFrame({'Nom': ['Hapsa', 'Elise', 'Xin','Amine'],'salaire': [90000, 100000, 80000, 100000]})
df6

Nom  salaire
0  Hapsa    90000
1  Elise   100000
2    Xin    80000
3  Amine   100000

In [129]:
print(pd.merge(df3, df6, left_on="Salarié", right_on="Nom"))

  Salarié      groupe  date_embauche    Nom  salaire
0   Hapsa   Ingénieur           2001  Hapsa    90000
1   Elise   Ingénieur           1988  Elise   100000
2     Xin  Technicien           2016    Xin    80000


In [130]:
df7 = pd.merge(df3, df6, left_on="Salarié", right_on="Nom").drop('Nom', axis=1)
df7

Salarié      groupe  date_embauche  salaire
0   Hapsa   Ingénieur           2001    90000
1   Elise   Ingénieur           1988   100000
2     Xin  Technicien           2016    80000

In [131]:
pd.merge(df3, df6, left_on="Salarié", right_on="Nom",how='outer').drop('Nom', axis=1)

Salarié      groupe  date_embauche   salaire
0    Eric  Technicien         2012.0       NaN
1   Hapsa   Ingénieur         2001.0   90000.0
2   Elise   Ingénieur         1988.0  100000.0
3     Xin  Technicien         2016.0   80000.0
4     NaN         NaN            NaN  100000.0

In [132]:
pd.merge(df3, df6, left_on="Salarié", right_on="Nom",how='left').drop('Nom', axis=1)

Salarié      groupe  date_embauche   salaire
0    Eric  Technicien           2012       NaN
1   Hapsa   Ingénieur           2001   90000.0
2   Elise   Ingénieur           1988  100000.0
3     Xin  Technicien           2016   80000.0

In [133]:
pd.merge(df3, df6, left_on="Salarié", right_on="Nom",how='right').drop('Nom', axis=1)

Salarié      groupe  date_embauche  salaire
0   Hapsa   Ingénieur         2001.0    90000
1   Elise   Ingénieur         1988.0   100000
2     Xin  Technicien         2016.0    80000
3     NaN         NaN            NaN   100000

In [137]:
df8 = pd.DataFrame({'Salarié': ['Eric', 'Hapsa', 'Elise', 'Xin'], 'Classement':[4,1,2,3]})
df9 = pd.DataFrame({'Salarié': ['Eric', 'Hapsa', 'Elise', 'Xin'], 'Classement':[4,1,3,2]})

In [135]:
pd.merge(df8, df9, on="Salarié")

Salarié  Classement_x  Classement_y
0    Eric             4             4
1   Hapsa             1             1
2   Elise             2             3
3     Xin             3             2

In [136]:
pd.merge(df8, df9, on="Salarié", suffixes=[" Novembre", " Décembre"])

Salarié  Classement Novembre  Classement Décembre
0    Eric                    4                    4
1   Hapsa                    1                    1
2   Elise                    2                    3
3     Xin                    3                    2

### Mettre en place des agrégations

In [138]:
import pandas as pd
import numpy as np

In [140]:
r = np.arange(0, 2, 0.2)
r

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [142]:
ser = pd.Series(r)
ser

0    0.0
1    0.2
2    0.4
3    0.6
4    0.8
5    1.0
6    1.2
7    1.4
8    1.6
9    1.8
dtype: float64

In [143]:
ser.sum()

9.000000000000002

In [144]:
ser.mean()

0.9000000000000001

In [145]:
ser.describe()

count    10.00000
mean      0.90000
std       0.60553
min       0.00000
25%       0.45000
50%       0.90000
75%       1.35000
max       1.80000
dtype: float64

In [146]:
df1 = pd.DataFrame({'A': ser[:4]+1, 'B': ser[4:]+2}).fillna({'A':1,'B':2})

In [147]:
df1

A    B
0  1.0  2.0
1  1.2  2.0
2  1.4  2.0
3  1.6  2.0
4  1.0  2.8
5  1.0  3.0
6  1.0  3.2
7  1.0  3.4
8  1.0  3.6
9  1.0  3.8

In [148]:
df1.mean()

A    1.12
B    2.78
dtype: float64

In [149]:
df1.mean(axis='columns')

0    1.5
1    1.6
2    1.7
3    1.8
4    1.9
5    2.0
6    2.1
7    2.2
8    2.3
9    2.4
dtype: float64

In [150]:
df1.describe()

A          B
count  10.000000  10.000000
mean    1.120000   2.780000
std     0.214994   0.726942
min     1.000000   2.000000
25%     1.000000   2.000000
50%     1.000000   2.900000
75%     1.150000   3.350000
max     1.600000   3.800000

In [151]:
df2 = pd.DataFrame({'étudiant': ['A', 'B', 'C', 'A', 'B', 'C'], 'notes': np.random.randint(12,18,6)}, columns=['étudiant', 'notes'])

In [152]:
df2

étudiant  notes
0        A     15
1        B     17
2        C     17
3        A     16
4        B     16
5        C     12

In [153]:
df2.groupby('étudiant').sum()

notes
étudiant       
A            31
B            33
C            29

In [154]:
df2.groupby('étudiant').describe()

notes                                                
         count  mean       std   min    25%   50%    75%   max
étudiant                                                      
A          2.0  15.5  0.707107  15.0  15.25  15.5  15.75  16.0
B          2.0  16.5  0.707107  16.0  16.25  16.5  16.75  17.0
C          2.0  14.5  3.535534  12.0  13.25  14.5  15.75  17.0

In [155]:
def fonction_filtre(v): return v['notes'].median() > 14

In [156]:
df2.groupby('étudiant').filter(fonction_filtre)

étudiant  notes
0        A     15
1        B     17
2        C     17
3        A     16
4        B     16
5        C     12

In [157]:
moyennes = df2.groupby('étudiant').mean().add_prefix('moyenne_')

In [158]:
moyennes

moyenne_notes
étudiant               
A                  15.5
B                  16.5
C                  14.5

### Séries Temporelles

In [159]:
import pandas as pd
import numpy as np

In [160]:
from datetime import datetime

In [161]:
d1=datetime(year=2014, month=10, day=9)

In [162]:
d1

datetime.datetime(2014, 10, 9, 0, 0)

In [163]:
d1.strftime('%A')

'Thursday'

In [165]:
d2 = np.array('2014-10-09', dtype=np.datetime64)

In [166]:
d2 + np.arange(6)

array(['2014-10-09', '2014-10-10', '2014-10-11', '2014-10-12',
       '2014-10-13', '2014-10-14'], dtype='datetime64[D]')

In [167]:
np.datetime64('2014-10-09 01:00')

numpy.datetime64('2014-10-09T01:00')

In [168]:
d3 = pd.to_datetime("9th of October, 2014")

In [169]:
d3

Timestamp('2014-10-09 00:00:00')

In [170]:
d3.strftime('%A')

'Thursday'

In [171]:
index1 = pd.DatetimeIndex(['2014-10-09', '2014-11-10','2015-10-11', '2015-11-12'])

In [172]:
d5 = pd.Series([0, 1, 2, 3], index=index1)

In [173]:
d5

2014-10-09    0
2014-11-10    1
2015-10-11    2
2015-11-12    3
dtype: int64

In [174]:
d5[:'2015-10-11']

2014-10-09    0
2014-11-10    1
2015-10-11    2
dtype: int64

In [175]:
d5['2014-11-10':'2015-10-11']

2014-11-10    1
2015-10-11    2
dtype: int64

In [176]:
d5['2014']

2014-10-09    0
2014-11-10    1
dtype: int64

In [177]:
pd.date_range('2014-10-09', '2014-10-15')

DatetimeIndex(['2014-10-09', '2014-10-10', '2014-10-11', '2014-10-12',
               '2014-10-13', '2014-10-14', '2014-10-15'],
              dtype='datetime64[ns]', freq='D')